### PR TITLE
backend delanswerandfollowing test and test_runner fixes

### LINKED ISSUE #217: backend: test_runner > verifysession: tests are passing when mismatching session file content
currently we only check if the line numbers match, but not if the lines actual match char by char

see #216

### PR DESCRIPTION
**Pull request by RoboSparrow**
- temporary fix for error overflow issue #198
- tests for delanswerandfollowing #186
- #217 add strcmp(session_line,comparasion_line) to test runner
- fix some existing tests (yes, most of them are mine:))
- fix #217 set `deleteFollowingP` arg to `1` in fcgi_delanswerandfollowing

- #147 improve `nextquestion` error detection, add support for `def cmodule_traceback(exc_type, exc_value, exc_tb)` for logging error tracebacks

There seems to be no convenient way to serialise this via the bindings, it always results in a null pointer or a stringified handler like `<traceback object at 0x7f1e184f2f48>`

example: 

```python
'''
 returns a printable traceback string for a given error
'''
def cmodule_traceback(exc_type, exc_value, exc_tb):
    import sys, traceback
    lines = []; 
    lines = traceback.format_exception(exc_type, exc_value, exc_tb)
    output = '\n'.join(lines)
    return output
```

### CODE REVIEW

**Comment by RoboSparrow** [comment]
merging after discussing with @gardners,  commit  9d918bf remember_error is temporary and #217 will be handled in #261

File: backend/src/fcgimain.c [hunk 1]
```diff
@@ -805,7 +805,7 @@ static void fcgi_delanswerandfollowing(struct kreq *req)
     }
     else if (question&&question->val) {
       // No answer give, so delete all answers to the given question
-      if (session_delete_answers_by_question_uid(s,question->val,0)<0) {
+      if (session_delete_answers_by_question_uid(s,question->val,1)<0) {
```
Comment (gardners) [inline backend/src/fcgimain.c:808]: What is the meaning of this change?

**Review by gardners — COMMENTED** [review]
Looks fine to me. Just that one change that I don't understand the intention and effect of.

File: backend/src/fcgimain.c (hunk 1 above)
Comment (RoboSparrow) [reply backend/src/fcgimain.c:808]: This is old... I turns on deleting of successor answers by default, effectively rolling back the survey state to that answer uid. All questions after that uid have to be reanswered (they provide old answer values as default value)
Otherwise nextquestion logic has trouble to deal with changed answer values

since #462 this flag is removed alltogether
